# permissions for end users to edit etcdclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: etcdcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: etcdop
    app.kubernetes.io/part-of: etcdop
    app.kubernetes.io/managed-by: kustomize
  name: etcdcluster-editor-role
rules:
- apiGroups:
  - etcd.cicd.com
  resources:
  - etcdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.cicd.com
  resources:
  - etcdclusters/status
  verbs:
  - get
